sudo: required
services:
    - docker
before_install:
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud outh activate-service-account --key-file sumitoma-account.json
    - gcloud config set project sumitoma
    - gcloud config set compute/zone us-central1-c 
    - gcloud container cluster get-credentials multi-cluster
    