apiVersion: v1
kind: Service #k8s object type to enable networking/communication between pods
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP # type of comm. i.e., NodePort(external to pods)/ClusterIP(b/w pods)/LoadBalancer(legacy alt for ingress)/Ingress
  selector: # to select the pods to which this service will be applied
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
