apiVersion: apps/v1
kind: Deployment #k8s object type to manage group of similar pods
metadata:
  name: postgres-deployment # deployment name
spec:
  replicas: 1 # number of pods to be created
  selector:
    matchLabels:
      component: postgres
  # pod template
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes: #to attach Volume Claim object to this pod
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres #will come from public repo from docker hub
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # where inside the conainer this storage should be available
              subPath: postgres #folder inside pvc where the data will be stored
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
