apiVersion: apps/v1apiVersion: apps/v1
kind: Deployment #k8s object type to manage group of similar pods
metadata:
    name: redis-deployment # deployment name
spec:
    replicas: 1 # number of pods to be created
    selector:
        matchLabels:
            component: redis
    # pod template
    template:
        metadata:
            labels:
                component: redis
        spec:
            containers:
                -   name: redis
                    image: redis #will come from public repo from docker hub     
                    ports:
                        -   containerPort: 6379