apiVersion: apps/v1
kind: Deployment #k8s object type to manage group of similar pods
metadata:
  name: worker-deployment # deployment name
spec:
  replicas: 1 # number of pods to be created
  selector:
    matchLabels:
      component: worker
  # pod template
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: sumitoma/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
